# Generated by Django 5.0.4 on 2024-04-13 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketsales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='Address',
            field=models.CharField(default='برج میلاد', max_length=500),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDatetime', models.DateTimeField()),
                ('Seats', models.IntegerField()),
                ('ConcertModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketsales.concertmodel')),
                ('LocationModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketsales.locationmodel')),
            ],
        ),
    ]
