# Generated by Django 5.0.4 on 2024-04-13 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketsales', '0002_alter_locationmodel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=100)),
                ('ProfileImage', models.ImageField(null=True, upload_to='ProfileImage/')),
                ('Gender', models.IntegerField(choices=[('Man', 'مرد'), ('Women', 'زن')])),
            ],
        ),
        migrations.AddField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='concertImage/'),
        ),
        migrations.AddField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[('start', 'فروش بلیط شروع شده است'), ('end', 'فروش بلیط تمام شده است'), ('Cancle', 'این سانس کنسل  شده است'), ('Sales', 'در حال فروش بلیط')], null=True),
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('TicketImage', models.ImageField(null=True, upload_to='TicketImages/')),
                ('ProfileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketsales.profilemodel')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketsales.timemodel')),
            ],
        ),
    ]
