# Generated by Django 5.0.4 on 2024-04-13 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketsales', '0003_profilemodel_concertmodel_poster_timemodel_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertmodel',
            options={'verbose_name': 'کنسرت', 'verbose_name_plural': 'کنسرت'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'محل برگزاری', 'verbose_name_plural': 'محل برگزاری'},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'شرکت کنندگان', 'verbose_name_plural': 'شرکت کنندگان'},
        ),
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'verbose_name': ' بلیط', 'verbose_name_plural': ' بلیط'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'زمان برگزاری', 'verbose_name_plural': 'زمان برگزاری'},
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Name',
            field=models.CharField(max_length=200, verbose_name='نام کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='SingerName',
            field=models.CharField(max_length=150, verbose_name='نام خواننده'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='lenght',
            field=models.IntegerField(verbose_name=' مدت زمان'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='concertImage/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Address',
            field=models.CharField(default='برج میلاد', max_length=500, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='مکان برگزاری'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Family',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Gender',
            field=models.IntegerField(choices=[('Man', 'مرد'), ('Women', 'زن')], verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='ProfileImage',
            field=models.ImageField(null=True, upload_to='ProfileImage/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نوع بلیط'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ProfileModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketsales.profilemodel', verbose_name='پروفایل'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='TicketImage',
            field=models.ImageField(null=True, upload_to='TicketImages/', verbose_name='تصویر بلیط'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='timeModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketsales.timemodel', verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='ConcertModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketsales.concertmodel', verbose_name='مدل کنسرت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='LocationModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketsales.locationmodel', verbose_name='مکان کنسرت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Seats',
            field=models.IntegerField(verbose_name='تعداد صندلی'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='StartDatetime',
            field=models.DateTimeField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[('start', 'فروش بلیط شروع شده است'), ('end', 'فروش بلیط تمام شده است'), ('Cancle', 'این سانس کنسل  شده است'), ('Sales', 'در حال فروش بلیط')], null=True, verbose_name='وضعیت'),
        ),
    ]
