# Generated by Django 5.0.4 on 2024-04-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketsales', '0004_alter_concertmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='ConcertImage', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='ConcertModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketsales.concertmodel', verbose_name='نام خواننده'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.CharField(choices=[('start', 'فروش بلیط شروع شده است'), ('end', 'فروش بلیط تمام شده است'), ('Cancle', 'این سانس کنسل  شده است'), ('Sales', 'در حال فروش بلیط')], max_length=50, null=True, verbose_name='وضعیت'),
        ),
    ]
